services:
  frontend:
    # build:
    # context: ./frontend
    image: mourad88/chat-app-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    # build:
    #   context: ./
    image: mourad88/chat-app-backend:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo:5
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
